const DEFAULT_PORT = process.env.PORT || 3000;
const DEFAULT_HEADER_CODE = 404;
const ERROR_HEADER_CODE = 500;
const DEFAULT_HEADER_CONTENT = { "content-type": "application/json" };

export { DEFAULT_PORT, DEFAULT_HEADER_CODE, ERROR_HEADER_CODE, DEFAULT_HEADER_CONTENT };
